version: "3"

services:
  app:
    container_name: edu-api-app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
